### ISSUE TITLE
not working out of the box (Win10)

### ISSUE THREAD

**Issue by j2l** [marborkowski/react-doc-generator#3]
npm install -save-dev react-doc-generator
```
capokey@0.0.0 E:\capokey
`-- react-doc-generator@1.2.5
  +-- cli-table@0.3.1
  | `-- colors@1.0.3
  +-- colors@1.1.2
  +-- commander@2.9.0
  | `-- graceful-readlink@1.0.1
  +-- handlebars@4.0.10
  | +-- async@1.5.2
  | `-- source-map@0.4.4
  |   `-- amdefine@1.0.1
  +-- node-dir@0.1.17
  +-- react-docgen@2.17.0
  | +-- babylon@5.8.38
  | +-- node-dir@0.1.17  deduped
  | `-- recast@0.12.6
  |   `-- ast-types@0.9.11
  `-- react-dom@15.6.1
```

then:
`npm run react-doc-generator src -o DOCUMENTATION.md`
```
npm ERR! missing script: react-doc-generator

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pm\AppData\Roaming\npm-cache\_logs\2017-09-05T10_27_38_117Z-debug.log
```

**Comment by joshdhenry** [comment]
+1 Same issue here on Mac OS X.

**Comment by j2l** [comment]
With -g, it still doesn't work for me on Win10

**Comment by marcochiang** [comment]
Yeah the only thing that worked for me is going into the node_module of react-doc-generator itself and running react-doc-generator {src} -o "DOC".md

**Comment by nelmarianna** [comment]
Had the same issue then I installed the module with -g and it worked as expected

**Comment by antoniojps** [comment]
One very dirty way of solving this is adding 

> `"react-doc-generator": "node_modules/react-doc-generator/dist/react-doc-generator.js"`

 to your scrips in the package.json file.

Then running react-doc-generator with

> npm run react-doc-generator

or

> yarn react-doc-generator

**Comment by CezaryDanielNowak** [comment]
https://github.com/CezaryDanielNowak/react-doc-generator
Please checkout this, works on Windows and has several improvements.

**Comment by j2l** [comment]
Thanks.
Meanwhile I switched to svelte.
